server:
  port: 8080
  contextPath: /rajput


spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./rajput-ticket-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
password:
  regexes: .*[A-Z]+.*:.*[a-z]+.*:.*[0-9]+.*:.*[\\W]+.*:.{8,12}
