## Reference at below link
## https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8080
  contextPath: /rajput


spring:
  flyway:
    schemas: TICKETING
    
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./rajput-ticket-db
    username: sa
    password:
    #schema: TICKETING //This will not work since the flyway is executed on the database connection, hence connection is initialized first.
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format-sql: true
      
      
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss Z #ISO Standard date format for JavaScript
    
#spring.data.web.pageable.default-page-size=20 # Default page size.
#spring.data.web.sort.sort-parameter=sort
      
password:
  regexes: .*[A-Z]+.*:.*[a-z]+.*:.*[0-9]+.*:.*[\\W]+.*:.{8,12}
