## Reference at below link
## https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8080
  servlet:
    context-path: /rajput


logging:
  level:
    org:
      springframework:
        web: INFO
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./rajput-ticket-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format-sql: true
      
      
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss Z #ISO Standard date format for JavaScript.
    
  data:
    web:
      pageable:
        default-page-size: 5 # Default page size is 20
    
password:
  regexes: .*[A-Z]+.*:.*[a-z]+.*:.*[0-9]+.*:.*[\\W]+.*:.{8,12}
