CREATE SCHEMA TICKETING;

CREATE TABLE TICKETING.USER (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  login_id VARCHAR(9) NOT NULL,
  email VARCHAR(25) NOT NULL,
  first_name VARCHAR(15) NOT NULL,
  middle_name VARCHAR(15),
  last_name VARCHAR(15) NOT NULL,
  type VARCHAR(5) DEFAULT 'USER' NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE TICKETING.USER_SECURITY (
  id BIGINT,
  password VARCHAR(100),
  created_at TIMESTAMP NOT NULL,
  last_login_at TIMESTAMP
);

CREATE TABLE TICKETING.ISSUE (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  reporter BIGINT NOT NULL,
  assignee BIGINT,
  created_at DATETIME NOT NULL,
  completed_at DATE
);

CREATE TABLE TICKETING.COMMENT (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  issue_id BIGINT NOT NULL,
  text VARCHAR(255) NOT NULL,
  commentator BIGINT NOT NULL,
  created_at DATETIME NOT NULL,
  last_modified_at DATETIME
);

ALTER TABLE TICKETING.USER_SECURITY
ALTER COLUMN created_at
SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TICKETING.USER
ALTER COLUMN updated_at
SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TICKETING.USER_SECURITY
ADD FOREIGN KEY (id)
REFERENCES TICKETING.USER(id);

ALTER TABLE TICKETING.COMMENT
ADD FOREIGN KEY (issue_id)
REFERENCES TICKETING.ISSUE(id);

ALTER TABLE TICKETING.ISSUE
ADD FOREIGN KEY (reporter)
REFERENCES TICKETING.USER(id);

ALTER TABLE TICKETING.ISSUE
ADD FOREIGN KEY (assignee)
REFERENCES TICKETING.USER(id);

INSERT INTO TICKETING.USER (login_id, first_name, last_name, email) VALUES ('prajput', 'Prishi', 'Rajput', 'prishi@rajput.me');
INSERT INTO TICKETING.USER (login_id, first_name, last_name, email) VALUES ('ssingh', 'Shivangi', 'Singh', 'shivanig@singh.me');
INSERT INTO TICKETING.USER (login_id, first_name, last_name, email) VALUES ('drajput', 'Deependra', 'Rajput', 'deependra@rajput.me');


INSERT INTO TICKETING.ISSUE (title, description, status, reporter, created_at)
VALUES (
    'Issue number one',
    'This is issue number one',
    'backlog',
    (select id from TICKETING.USER where USER.login_id = 'prajput'),
    '2017-08-01'
);

INSERT INTO TICKETING.ISSUE (title, description, status, reporter, created_at)
VALUES (
  'Issue number two',
  'This is issue number two',
  'backlog',
  (select id from TICKETING.USER where USER.login_id = 'ssingh'),
  '2017-08-01'
);

INSERT INTO TICKETING.ISSUE (title, description, status, reporter, assignee, created_at, completed_at)
VALUES (
  'Issue number three',
  'This is issue number three',
  'done',
  (select id from TICKETING.USER where USER.login_id = 'ssingh'),
  (select id from TICKETING.USER where USER.login_id = 'ssingh'),
  '2017-07-22',
  '2017-08-02'
);

INSERT INTO TICKETING.ISSUE (title, description, status, reporter, assignee, created_at, completed_at)
VALUES (
  'Issue number four',
  'This is issue number four',
  'done',
  (select id from TICKETING.USER where USER.login_id = 'prajput'),
  (select id from TICKETING.USER where USER.login_id = 'ssingh'),
  '2017-08-02',
  '2017-08-02'
);

INSERT INTO TICKETING.ISSUE (title, description, status, reporter, assignee, created_at)
VALUES (
  'Issue number five',
  'This is issue number five',
  'in_progress',
  (select id from TICKETING.USER where USER.login_id = 'ssingh'),
  (select id from TICKETING.USER where USER.login_id = 'drajput'),
  '2017-08-02'
);
